part of xpath_dart;

enum SyntaxNodeKind {
  UNDEFINED,
  ETNK_STEP,
  ETNK_DOUBLE_STEP,
  ETNK_FORWARD_AXIS,
  ETNK_REVERSE_AXIS,
  ETNK_NAME_TEST,
  ETNK_NODE_TEST,
  ETNK_LITERAL,
  ETNK_EXPR_SEQUENCE,
  ETNK_FUNCTION_CALL,
  ETNK_PATH_EXPR,
  ETNK_VARIABLE,
  ETNK_PREDICATE
}
